language: android

android:
  components:
  - build-tools-27.0.3
  - android-27

install:
- true

before_script:
- chmod +x gradlew
- echo "Travis branch is $TRAVIS_BRANCH"
- echo "Travis branch is in pull request? $TRAVIS_PULL_REQUEST"
- echo "Travis tag $TRAVIS_TAG"
- echo "org.gradle.daemon=false" >> gradle.properties
#- "docker pull $DOCKER_IMAGE"

stages:
  - name: compile
  - name: deploy
    if: tag IS present OR branch = master

jobs:
  include:
    - stage: compile
      script:
#      - "docker run -it -v $PWD:/workspace $DOCKER_IMAGE /bin/sh -c \"cd /workspace && ./gradlew clean build\""
      - ./gradlew clean build
      - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      script:
      - openssl aes-256-cbc -K $encrypted_f3f9bf37f66c_key -iv $encrypted_f3f9bf37f66c_iv
         -in maven.keystore.gpg.enc -out maven.keystore.gpg -d
      - echo -e "signing.keyId=${SIGNING_KEY}" >> "gradle.properties"
      - echo -e "signing.password=${SIGNING_PASSWORD}" >> "gradle.properties"
#      - echo -e "signing.secretKeyRingFile=../maven.keystore.gpg" >> "gradle.properties"
      - ./gradlew uploadArchives --debug
#      - echo -e "SONATYPE_USERNAME=${SONATYPE_USERNAME}" >> docker.env
#      - echo -e "SONATYPE_PASSWORD=${SONATYPE_PASSWORD}" >> docker.env
#      - echo -e "TRAVIS_TAG=${TRAVIS_TAG}" >> docker.env
#      - echo -e "TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}" >> docker.env
#      - "docker run -it --env-file docker.env -v $PWD:/workspace $DOCKER_IMAGE /bin/sh -c \"cd /workspace && ./gradlew uploadArchives\""
