
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: toxicbakery/alpine-glibc-android:release-2.0
  environment:
    TERM: dumb

branches:
  ignore:
    - gh-pages

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Execute Gradle
          command: |
            echo "org.gradle.parallel=false" >> gradle.properties
            echo "kotlin.incremental=false" >> gradle.properties
            if [ "master" = "$CIRCLE_BRANCH" ] || [ ! -z "$CIRCLE_TAG" ]; then
              echo "signing.keyId=${SIGNING_KEY}" >> "gradle.properties"
              echo "signing.password=${SIGNING_PASSWORD}" >> "gradle.properties"
              echo "signing.secretKeyRingFile=../maven.keystore" >> "gradle.properties"
              echo "signing.secretKeyRingFile=../../maven.keystore" >> "tools/gradle.properties"
              gpg --cipher-algo AES256 --yes --batch --passphrase=$ENC_FILE_KEY maven.keystore.gpg
              cp maven.keystore tools/maven.keystore
              ./gradlew build dokkaGhPages publish --no-daemon
              if [ "master" = "$CIRCLE_BRANCH" ]; then
                git config --global user.email $GH_EMAIL
                git config --global user.name $GH_NAME
                cp -r .circleci core/gh-pages/.circleci
                cd core/gh-pages
                git init 
                git checkout --orphan gh-pages
                git add -A
                git commit -m "Automated deployment of ${CIRCLE_BRANCH} ${CIRCLE_SHA1}" --allow-empty
                git push -q https://${GH_PERSONAL_TOKEN}@github.com/ToxicBakery/${CIRCLE_PROJECT_REPONAME}.git gh-pages --force
              fi
            else
              ./gradlew build --no-daemon
            fi
            bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Sonatype
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - gh-pages
